version: '3'
services:
  heudiconv:
    image: nipy/heudiconv:latest
    # networks:
      # - workbench
    volumes:
      - datos-dicom:/data:ro
      - niix-output:/output
volumes:
  datos-dicom:
  niix-output:
