version: '3'
services:
  namenode:
    image: nipy/heudiconv:latest
    # networks:
      # - workbench
    volumes:
      - datos-dicom:/data:ro
      - niix-output:/output
    environment:
      - d: /data/{subject}/T0041/DICOM/14021913/*/*
      - s: T004
      - ses: 11280000
      - f: output/code/convertall_elekin.py
      - c: dcm2niix 
      - b: 
      - overwrite:
      
    deploy:
      mode: global
      replicas: 1
      restart_policy:
        condition: on-failure
      # add placement constraint to allocate namenode on particular server
      #placement:
      #  constraints:
      #    - node.hostname == master.node.com
      # labels:
        # traefik.docker.network: workbench
        # traefik.port: 50070


volumes:
  datos-dicom:
  niix-output:
