properties([pipelineTriggers([githubPush()])])
node {
    def img
    docker.withServer("${SERVER}") {
    stage ("Get source from Git"){
        git branch:"develop",url:"https://github.com/spolex/docker-pyrestfmri.git"
    }
    stage ("Generate Dockerfile") {
     sh "hostname"
     sh "ls jupyter"
     }
   }
}
