properties([pipelineTriggers([githubPush()])])
node {
    def img
    docker.withServer("${SERVER}") {
    stage ("Get source from Git"){
        git branch:"develop",url:"https://github.com/spolex/docker-pyrestfmri.git"
    }
    stage ("Generate Dockerfile") {
     sh "hostname"
     sh "./jupyter/generate_jupyter_docker.sh > Dockerfile"
     }
    stage ("Build image") {
            img = docker.build("spolex/pyrestfmri-lab:${VERSION}.${env.BUILD_NUMBER}", "--network host --no-cache .")
            docker.build("spolex/pyrestfmri-lab:latest", "--network host .")
     }
     stage('Test image') {
        /* Ideally, we would run a test framework against our image.*/
        img.inside {
            sh 'echo "Tests passed"'
        }
    }
     stage ("Run pyrestfmri container"){
            img.run('--name pyrestfmri-lab -v ${DATA_PATH}:/home/elekin/datos \
            -p 8888:8888 \
            -v ${APP_PATH}:/home/elekin/pyrestfmri  \
            -v ${RESULTS}:/home/elekin/results', \
            '${APP}')
      }
    }
}