properties([pipelineTriggers([githubPush()])])
node {
    docker.withServer("${SERVER}") {
    stage ("Get source from Git"){
        git branch:"develop",url:"https://github.com/spolex/docker-pyrestfmri.git"
    }
    stage ("Generate Dockerfile") {
     sh "hostname"
     sh "./pyrestfmri/generate_docker.sh > Dockerfile"
     }
    stage ("Build image") {
            docker.build('spolex/pyrestfmri:0.1')
        }
    }
}